// apps/templates/bambi-svelte/src/App.svelte
<script lang="ts">
import { Button } from "./components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./components/ui/tabs";
</script>

<div>
  bambiui-svelte
  <Button variant="secondary">Button</Button>
  <Tabs defaultValue="account">
    <TabsList>
      <TabsTrigger value="account">Account</TabsTrigger>
      <TabsTrigger value="password">Password</TabsTrigger>
    </TabsList>
    <TabsContent value="account">
      <p>Account content</p>
    </TabsContent>
    <TabsContent value="password">
      <p>Password content</p>
    </TabsContent>
  </Tabs>
</div>

// apps/templates/bambi-vue/app.vue
<script setup lang="ts">
import { Button } from "./src/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./src/components/ui/tabs";
</script>

<template>
  <div>
    bambiui-vue
    <Button variant="secondary">Button</Button>
    <Tabs default-value="password">
      <TabsList>
        <TabsTrigger value="account">Account</TabsTrigger>
        <TabsTrigger value="password">Password</TabsTrigger>
      </TabsList>
      <TabsContent value="account">
        <p>Account content</p>
      </TabsContent>
      <TabsContent value="password">
        <p>Password content</p>
      </TabsContent>
    </Tabs>
  </div>
</template>
