// apps/templates/bambi-vue/src/components/ui/tabs/tabs-trigger.vue
<script setup lang="ts">
const props = defineProps<{
  value: string;
  class?: string;
  disabled?: boolean;
}>();
</script>

<template>
  <button
    role="tab"
    type="button"
    data-bambi-tabs-trigger
    :data-value="value"
    :data-disabled="disabled ? 'true' : undefined"
    :disabled="disabled"
    :class="props.class"
  >
    <slot />
  </button>
</template>

// apps/templates/bambi-svelte/src/components/ui/tabs/components/tabs-trigger.svelte
<script lang="ts">
  interface Props {
    value: string;
    class?: string;
    disabled?: boolean;
    children?: import("svelte").Snippet;
  }
  let { value, class: className, disabled, children }: Props = $props();
</script>

<button
  role="tab"
  type="button"
  data-bambi-tabs-trigger=""
  data-value={value}
  data-disabled={disabled ? "true" : undefined}
  {disabled}
  class={className}
>
  {@render children?.()}
</button>
