// packages/registry/src/components/tabs/solid/tabs.solid.tsx
import "./tabs.css";
import { createEffect, onCleanup, type JSX } from "solid-js";
import { TabsController } from "@bambiui/core/components/tabs";
import type { TabsOptions } from "@bambiui/core/components/tabs";

export type { BambiController, TabsOptions, TabsOrientation } from "@bambiui/core/components/tabs";
export type { TabsValueChangeDetail } from "@bambiui/core/components/tabs";

export interface TabsProps extends Omit<TabsOptions, "onValueChange"> {
  children?: JSX.Element;
  class?: string;
  onValueChange?: (value: string) => void;
}

export function Tabs(props: TabsProps) {
  let rootEl: HTMLDivElement | undefined;
  let controller: TabsController | undefined;
  const isControlled = () => props.controlled ?? props.value !== undefined;

  createEffect(() => {
    if (!rootEl) return;
    controller = new TabsController(rootEl, {
      value: props.value,
      defaultValue: props.defaultValue,
      controlled: isControlled(),
      orientation: props.orientation ?? "horizontal",
      disabled: props.disabled,
      onValueChange: props.onValueChange,
    });
    controller.sync();
    onCleanup(() => controller?.destroy());
  });

  createEffect(() => {
    controller?.update({
      value: props.value,
      disabled: props.disabled,
      orientation: props.orientation,
      onValueChange: props.onValueChange,
    });
  });

  return (
    <div
      ref={rootEl}
      data-bambi-tabs=""
      data-orientation={props.orientation ?? "horizontal"}
      data-controlled={isControlled() ? "true" : "false"}
      class={props.class}
    >
      {props.children}
    </div>
  );
}

export interface TabsListProps {
  children?: JSX.Element;
  class?: string;
}

export function TabsList(props: TabsListProps) {
  return (
    <div role="tablist" data-bambi-tabs-list="" class={props.class}>
      {props.children}
    </div>
  );
}

export interface TabsTriggerProps {
  value: string;
  children?: JSX.Element;
  class?: string;
  disabled?: boolean;
}

export function TabsTrigger(props: TabsTriggerProps) {
  return (
    <button
      role="tab"
      type="button"
      data-bambi-tabs-trigger=""
      data-value={props.value}
      data-disabled={props.disabled ? "true" : undefined}
      disabled={props.disabled}
      class={props.class}
    >
      {props.children}
    </button>
  );
}

export interface TabsContentProps {
  value: string;
  children?: JSX.Element;
  class?: string;
}

export function TabsContent(props: TabsContentProps) {
  return (
    <div
      role="tabpanel"
      data-bambi-tabs-content=""
      data-value={props.value}
      class={props.class}
      tabIndex={0}
    >
      {props.children}
    </div>
  );
}

// packages/registry/src/components/tabs/react/tabs.react.tsx
import { useEffect, useRef, type ReactNode } from "react";
import { TabsController } from "@bambiui/core/components/tabs";
import type { TabsOptions } from "@bambiui/core/components/tabs";
import "./tabs.css";

export type { BambiController, TabsOptions, TabsOrientation } from "@bambiui/core/components/tabs";
export type { TabsValueChangeDetail } from "@bambiui/core/components/tabs";

export interface TabsProps extends TabsOptions {
  children?: ReactNode;
  className?: string;
}

export function Tabs({
  children,
  className,
  value,
  defaultValue,
  controlled,
  orientation = "horizontal",
  disabled,
  onValueChange,
}: TabsProps) {
  if (value !== undefined && defaultValue !== undefined) {
    console.warn(
      "[bambiui/tabs] Tabs received both `value` and `defaultValue`. " +
        "Use `value` for controlled mode or `defaultValue` for uncontrolled mode, not both.",
    );
  }

  const rootRef = useRef<HTMLDivElement>(null);
  const controllerRef = useRef<TabsController | null>(null);
  const isControlled = controlled ?? value !== undefined;

  useEffect(() => {
    const el = rootRef.current;
    if (!el) return;
    const controller = new TabsController(el, {
      value,
      defaultValue,
      controlled: isControlled,
      orientation,
      disabled,
      onValueChange,
    });
    controller.sync();
    controllerRef.current = controller;
    return () => {
      controller.destroy();
      controllerRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    controllerRef.current?.update({ value, disabled, orientation, onValueChange });
  }, [value, disabled, orientation, onValueChange]);

  return (
    <div
      ref={rootRef}
      data-bambi-tabs=""
      data-orientation={orientation}
      data-controlled={isControlled ? "true" : "false"}
      className={className}
    >
      {children}
    </div>
  );
}

export interface TabsListProps {
  children?: ReactNode;
  className?: string;
}

export function TabsList({ children, className }: TabsListProps) {
  return (
    <div role="tablist" data-bambi-tabs-list="" className={className}>
      {children}
    </div>
  );
}

export interface TabsTriggerProps {
  value: string;
  children?: ReactNode;
  className?: string;
  disabled?: boolean;
}

export function TabsTrigger({ value, children, className, disabled }: TabsTriggerProps) {
  return (
    <button
      role="tab"
      type="button"
      data-bambi-tabs-trigger=""
      data-value={value}
      data-disabled={disabled ? "true" : undefined}
      disabled={disabled}
      className={className}
    >
      {children}
    </button>
  );
}

export interface TabsContentProps {
  value: string;
  children?: ReactNode;
  className?: string;
}

export function TabsContent({ value, children, className }: TabsContentProps) {
  return (
    <div
      role="tabpanel"
      data-bambi-tabs-content=""
      data-value={value}
      className={className}
      tabIndex={0}
    >
      {children}
    </div>
  );
}
