// apps/templates/bambi-vue/src/components/ui/tabs/TabsContent.vue
<script setup lang="ts">
defineOptions({ inheritAttrs: false });
import { computed, inject, type ComputedRef } from "vue";
interface Props {
  value: string;
}
const props = defineProps<Props>();

const selectedValue = inject<ComputedRef<string | undefined>>("bambi-tabs-value");
const hasSelectedValue = computed(() => selectedValue?.value !== undefined);
const isSelected = computed(() => selectedValue?.value === props.value);
</script>
<template>
  <div
    v-bind="$attrs"
    data-bambi-tabs-content=""
    :data-value="props.value"
    :role="'tabpanel'"
    :data-state="hasSelectedValue ? (isSelected ? 'active' : 'inactive') : undefined"
    :hidden="hasSelectedValue ? (isSelected ? false : true) : undefined"
  >
    <slot />
  </div>
</template>

// apps/templates/bambi-svelte/src/components/ui/tabs/tabs-content.svelte
<script lang="ts">
  interface Props {
    value: string;
    class?: string;
    children?: import("svelte").Snippet;
  }
  let { value, class: className, children }: Props = $props();
</script>

<div
  role="tabpanel"
  data-bambi-tabs-content=""
  data-value={value}
  class={className}
  tabindex="0"
>
  {@render children?.()}
</div>
