// apps/templates/bambi-svelte/src/components/ui/tabs/TabsContent.svelte
<script lang="ts">
import { getContext, type Snippet } from "svelte";

interface Props {
  value: string;
  children?: Snippet;
  [key: string]: unknown;
}
let { value, children, ...props }: Props = $props();

const selectedValue = getContext<(() => string | undefined) | undefined>("bambi-tabs-value");
const hasSelectedValue = $derived(selectedValue?.() !== undefined);
const isSelected = $derived(selectedValue?.() === value);
</script>
<div
  {...props}
  data-bambi-tabs-content=""
    data-value={value}
    role={"tabpanel"}
    data-state={hasSelectedValue ? (isSelected ? "active" : "inactive") : undefined}
    hidden={hasSelectedValue ? (isSelected ? false : true) : undefined}
>
  {@render children?.()}
</div>

// apps/templates/bambi-vue/src/components/ui/tabs/TabsContent.vue
<script setup lang="ts">
defineOptions({ inheritAttrs: false });
import { computed, inject, type ComputedRef } from "vue";
interface Props {
  value: string;
}
const props = defineProps<Props>();

const selectedValue = inject<ComputedRef<string | undefined>>("bambi-tabs-value");
const hasSelectedValue = computed(() => selectedValue?.value !== undefined);
const isSelected = computed(() => selectedValue?.value === props.value);
</script>
<template>
  <div
    v-bind="$attrs"
    data-bambi-tabs-content=""
    :data-value="props.value"
    :role="'tabpanel'"
    :data-state="hasSelectedValue ? (isSelected ? 'active' : 'inactive') : undefined"
    :hidden="hasSelectedValue ? (isSelected ? false : true) : undefined"
  >
    <slot />
  </div>
</template>
