// apps/templates/bambi-svelte/src/components/ui/tabs/components/tabs-trigger.svelte
<script lang="ts">
  interface Props {
    value: string;
    class?: string;
    disabled?: boolean;
    children?: import("svelte").Snippet;
  }
  let { value, class: className, disabled, children }: Props = $props();
</script>

<button
  role="tab"
  type="button"
  data-bambi-tabs-trigger=""
  data-value={value}
  data-disabled={disabled ? "true" : undefined}
  {disabled}
  class={className}
>
  {@render children?.()}
</button>

// apps/templates/bambi-vue/src/components/ui/tabs/TabsTrigger.vue
<script setup lang="ts">
defineOptions({ inheritAttrs: false });
interface Props {
  value: string;
  disabled?: boolean;
}
const props = defineProps<Props>();
</script>
<template>
  <button
      type="button"
      :disabled="props.disabled"
      :data-disabled="props.disabled ? 'true' : undefined"
    data-bambi-tabs-trigger=""
      :data-value="props.value"
    v-bind="$attrs"
  >
    <slot />
  </button>
</template>
