// packages/registry/generated/radio-group/svelte/RadioGroupItem.svelte
<script lang="ts">
import { getContext, type Snippet } from "svelte";

interface Props {
  value: string;
  disabled?: boolean;
  children?: Snippet;
  [key: string]: unknown;
}
let { value, disabled, children, ...props }: Props = $props();

const selectedValue = getContext<(() => string | undefined) | undefined>("bambi-radio-group-value");
const hasSelectedValue = $derived(selectedValue?.() !== undefined);
const isSelected = $derived(selectedValue?.() === value);
</script>
<div
  {...props}
    data-disabled={disabled ? "true" : undefined}
  data-bambi-radio-group-item=""
    data-value={value}
    data-state={hasSelectedValue ? (isSelected ? "checked" : "unchecked") : undefined}
>
  <input
    data-bambi-radio-group-input=""
    type={"radio"}
    value={value}
    disabled={disabled}
    checked={hasSelectedValue ? isSelected : undefined}
    readonly={true}
  />
  {@render children?.()}
</div>

// apps/templates/bambi-vue/src/components/ui/radio-group/RadioGroupItem.vue
<script setup lang="ts">
defineOptions({ inheritAttrs: false });
import { computed, inject, type ComputedRef } from "vue";
interface Props {
  value: string;
  disabled?: boolean;
}
const props = defineProps<Props>();

const selectedValue = inject<ComputedRef<string | undefined>>("bambi-radio-group-value");
const hasSelectedValue = computed(() => selectedValue?.value !== undefined);
const isSelected = computed(() => selectedValue?.value === props.value);
</script>
<template>
  <div
    v-bind="$attrs"
    :data-disabled="props.disabled ? 'true' : undefined"
    data-bambi-radio-group-item=""
    :data-value="props.value"
    :data-state="hasSelectedValue ? (isSelected ? 'checked' : 'unchecked') : undefined"
  >
    <input
      data-bambi-radio-group-input=""
      :type="'radio'"
      :value="props.value"
      :disabled="props.disabled"
      :checked="hasSelectedValue ? isSelected : undefined"
      :readonly="true"
    />

    <slot />
  </div>
</template>
