// apps/templates/bambi-svelte/src/components/ui/button/Button.svelte
<script lang="ts">
  import type { HTMLButtonAttributes } from "svelte/elements";
  import { buttonRecipe } from "./recipe";
  import type { ButtonBaseProps } from "./types";
  import "./button.css";

  interface Props extends HTMLButtonAttributes, ButtonBaseProps {
    class?: string;
  }

  let {
    children,
    type = "button",
    intent = buttonRecipe.defaults.intent,
    appearance = buttonRecipe.defaults.appearance,
    size = buttonRecipe.defaults.size,
    loading = buttonRecipe.defaults.loading,
    disabled,
    class: className,
    ...attrs
  }: Props = $props();

  const cls = $derived(
    [buttonRecipe.className, className].filter(Boolean).join(" ")
  );
  const isLoading = $derived(Boolean(loading));
  const isDisabled = $derived(Boolean(disabled || isLoading));
</script>

<button
  {...attrs}
  {type}
  class={cls}
  data-intent={intent}
  data-appearance={appearance}
  data-size={size}
  data-loading={isLoading || undefined}
  aria-busy={isLoading || undefined}
  aria-disabled={isDisabled || undefined}
  disabled={isDisabled}
>
  {#if isLoading}
    <span class="bambi-button-spinner" aria-hidden="true"></span>
  {/if}
  <span class="bambi-button-content">
    {@render children?.()}
  </span>
</button>

// apps/templates/next-bambi-template/src/components/ui/button/button.tsx
import { forwardRef, type ButtonHTMLAttributes } from "react";
import { buttonRecipe } from "./recipe";
import type { ButtonBaseProps } from "./types";
import "./button.css";

export type {
  ButtonAppearance,
  ButtonBaseProps,
  ButtonIntent,
  ButtonSize,
} from "./types";

function cn(...inputs: Array<string | false | null | undefined>) {
  return inputs.filter(Boolean).join(" ");
}

export interface ButtonProps
  extends ButtonHTMLAttributes<HTMLButtonElement>, ButtonBaseProps {}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  function Button(
    {
      children,
      className,
      type = "button",
      intent = buttonRecipe.defaults.intent,
      appearance = buttonRecipe.defaults.appearance,
      size = buttonRecipe.defaults.size,
      loading = buttonRecipe.defaults.loading,
      disabled,
      ...props
    },
    ref,
  ) {
    const isLoading = Boolean(loading);
    const isDisabled = Boolean(disabled || isLoading);

    return (
      <button
        ref={ref}
        type={type}
        data-intent={intent}
        data-appearance={appearance}
        data-size={size}
        data-loading={isLoading || undefined}
        aria-busy={isLoading || undefined}
        aria-disabled={isDisabled || undefined}
        disabled={isDisabled}
        className={cn(buttonRecipe.className, className)}
        {...props}
      >
        {isLoading && (
          <span className="bambi-button-spinner" aria-hidden="true" />
        )}
        <span className="bambi-button-content">{children}</span>
      </button>
    );
  },
);
