// packages/components/input/src/input.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue";
import { inputRecipe } from "./recipe";
import "./input.css";

defineOptions({ name: "BambiInput", inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    class?: string;
    id?: string;
    /** Marks the input as invalid; sets aria-invalid="true". */
    invalid?: boolean;
    ariaDescribedby?: string;
    ariaInvalid?: string | boolean;
  }>(),
  {
    class: undefined,
    id: undefined,
    invalid: false,
    ariaDescribedby: undefined,
    ariaInvalid: undefined,
  },
);

const attrs = useAttrs();

const cls = computed(() =>
  [inputRecipe.elementClassName, props.class].filter(Boolean).join(" "),
);

const resolvedInvalid = computed<boolean | "grammar" | "spelling" | undefined>(
  () => {
    if (props.ariaInvalid !== undefined) return Boolean(props.ariaInvalid) || undefined;
    return props.invalid ? true : undefined;
  },
);
</script>

<template>
  <input
    v-bind="attrs"
    :id="props.id"
    :class="cls"
    :aria-describedby="props.ariaDescribedby"
    :aria-invalid="resolvedInvalid"
  />
</template>

// packages/components/input/src/input.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from "svelte/elements";
  import { inputRecipe } from "./recipe";
  import "./input.css";

  interface Props extends Omit<HTMLInputAttributes, "size"> {
    class?: string;
    /** Marks the input as invalid; sets aria-invalid="true". */
    invalid?: boolean;
  }

  let {
    class: className,
    invalid,
    id,
    "aria-describedby": ariaDescribedBy,
    "aria-invalid": ariaInvalid,
    ...attrs
  }: Props = $props();

  const resolvedInvalid = $derived(
    ariaInvalid !== undefined ? ariaInvalid : invalid ? "true" : undefined,
  );
  const cls = $derived(
    [inputRecipe.elementClassName, className].filter(Boolean).join(" "),
  );
</script>

<input
  {...attrs}
  {id}
  class={cls}
  aria-describedby={ariaDescribedBy}
  aria-invalid={resolvedInvalid}
/>
