// apps/templates/bambi-svelte/src/components/ui/tabs/TabsTrigger.svelte
<script lang="ts">
import { type Snippet } from "svelte";

interface Props {
  value: string;
  disabled?: boolean;
  type?: "button" | "submit" | "reset";
  children?: Snippet;
  [key: string]: unknown;
}
let { value, disabled, type = "button", children, ...props }: Props = $props();
</script>
<button
  {...props}
    type={type}
    disabled={disabled}
    data-disabled={disabled ? "true" : undefined}
  data-bambi-tabs-trigger=""
    data-value={value}
>
  {@render children?.()}
</button>

// packages/registry/generated/tabs/vue/TabsTrigger.vue
<script setup lang="ts">
interface Props {
  value: string;
  disabled?: boolean;
}
const props = defineProps<Props>();
</script>
<template>
  <button
      type="button"
      :disabled="props.disabled"
      :data-disabled="props.disabled ? 'true' : undefined"
    data-bambi-tabs-trigger=""
      :data-value="props.value"
    v-bind="$attrs"
  >
    <slot />
  </button>
</template>
